cache:
  mount:
    - .git

build:
  image: haskell:$$HASKELL_VERSION
  commands:
      - cabal update
      - cabal install --only-dependencies --enable-tests
      - cabal configure --enable-tests && cabal build && cabal test
      - ./dist/build/m3u-converter/m3u-converter test/sample.m3u --format yaml

matrix:
    HASKELL_VERSION:
        - 7.10.3
        - latest
